lsコマンド提出
pctapitapitapi/ruby-practices pull request #4
Opened 2021-09-11 05:05 UTC by pctapitapitapi

lsコマンドの課題を提出致します🙇‍♀️
ご確認何卒よろしくお願い致します🙏

2021-09-17 01:17 UTC, u1tnk requested changes
いくつか部分にコメントもしたのですが、全般的には以下を見直して欲しいです。

- メソッド名が内容とあっていない。
    - 例えばoption_aという名前のメソッドがあるが、やっている事は`option_aのときにはファイルを取得し直す`でやっている事のメインは「ファイルの取得」です。
    - option_a等は lsの仕様を知っている前提の名前ですが、仕事では仕様も膨大なので、より分かりやすい名前が必要です。 aならallの方が良いですね。
- メソッドをシンプルにする。似た名前のメソッドの内容を揃える、一つのメソッドに仕事をまとめすぎない。
    - built_list は「listのでデータを集めてまとめるのかな？」と思って読むと出力までしている。
    - option_l はリスト表示にするための何かをしているかと思ったら option_lのときの処理の残り全てを行なっている。

細かいところはまだありそうですが、全体的に見直して欲しいです 🙏 
機能はちゃんと満たしているので、「lsコマンドに詳しく無い人が読みやすいように」という視点でメソッド、変数の名前、構成を見直してみてください 💪

2021-09-17 01:17 UTC, u1tnk commented on 05.ls/ls.rb
> +  all_files = Dir.glob('*').sort
ここで共通で `Dir.glob`を実行しているのですが、`a`オプションのときはもう一回実行して無駄になっていますので、分岐して一回の実行でできるようにしましょう。

2021-09-17 01:17 UTC, u1tnk commented on 05.ls/ls.rb
> +  all_files_r = option_r(all_files_a, params)
ここは内容的には all_files_rでは無く、 `all_files_ar`になると思うので誤解を招きそうです。

こういう処理の場合は同じ変数で大丈夫ですよ。

```
  all_files = option_a(all_files, params)
  all_files = option_r(all_files_a, params)
...
```

2021-09-17 01:17 UTC, u1tnk commented on 05.ls/ls.rb
> +    built_option_l(all_files_r)
option_lのときはここで、通常時はmainで `built_option_xxx`を読んでいるのが分かりずらいです。
同じ機能であれば並列で分岐しているのが分かりやすいようにしましょう。

2021-09-20 03:37 UTC, pctapitapitapi commented
ご確認頂きありがとうございます🙏

頂いたご指摘を参考に、メソッド名の変更とメソッドの再構成を致しました！
`show_detailed_list`と`show_list`のメソッドについて、本当はもっと細分化したいなと思ったのですが、
良い方法が思いつかなかったのでご教示頂ければ幸いです🙇‍♀️

お忙しい中恐れ入りますが、ご確認よろしくお願い致します！

2021-09-20 11:56 UTC, u1tnk requested changes
show_detailed_list/show_listを短くする方法ですが、
簡単にやるなら、それぞれ each内で一行分の出力処理を、例えば `show_list_per_line`とかで分割するぐらいでしょうか。

もっと頑張るならデータ作成と出力を完全に分けると良いですね。
detailed_list/普通のlist両方に必要な情報を先に全部取りだして、データ化するところは共通化しておいて、出力するときに分岐すると良いです。

ちょっと難しいのでデータのイメージを書いとくと以下みたいな感じですね。
```
{
  "all": {...} # 合計サイズ等の合計情報
  "files": [{name: ....}, ...]
}
```

前者の方でプラクティス的には十分OKレベルです。
こだわるなら後者でも良いですが、オブジェクト指向版もありますし、無理しなくても大丈夫です 🙆‍♀️

2021-09-20 11:56 UTC, u1tnk commented on 05.ls/ls.rb
> +  if params.empty?
小ネタですけど 
```
return show_list(all_files) if params.empty?
```

で大丈夫ですね。

ただ、 

```
return if xxxx
```
であればほぼやりますけど、 returnの後に処理があると見づらいので書かないという人も居るので参考まで。

2021-09-20 11:56 UTC, u1tnk commented on 05.ls/ls.rb
> +  detailed_list = {}
detailed_list 変数は毎行上書きされるので、ブロックの中で定義するべきだと思います。
ブロック外で定義すると、ブロック一回の実行後に残ってしまうので意図しない影響の可能性が発生してしまいます。

2021-09-21 01:42 UTC, pctapitapitapi commented
ご教示頂きありがとうございます🙏

> 簡単にやるなら、それぞれ each内で一行分の出力処理を、例えば show_list_per_lineとかで分割するぐらいでしょうか。

今回の修正の通り理解しましたが、もし認識齟齬ありましたらご指摘お願い致します🙇‍♀️

> データ作成と出力を完全に分けると良いですね。
detailed_list/普通のlist両方に必要な情報を先に全部取りだして、データ化するところは共通化しておいて、出力するときに分岐すると良いです。

本当はこちらでおっしゃる通りのことがしたかったです😅
例えば下記の箇所
```ruby
def show_list_per_line(sliced_files, max_length)
  sliced_files.transpose.each do |files_element|
    file_names = []
    files_element.each do |file_element|
      lack_of_space = max_length - file_element.length
      file_name = file_element.ljust(lack_of_space + file_element.length, ' ')
      file_names << file_name
    end
    print file_names.join(' ')
    puts
  end
end
```
- 別のメソッドに切り出して`file_names`を作る。
- `show`メソッドで、`file_names`の出力だけを行う。

しかし、今の私のコードだとeachの中で一緒に出力して動いているコードなので、これを分割すると動かなくなってしまう🤔
頂いたイメージを見てもピンとこなかったので😂
今回は前者の対応と致しました🙇‍♀️
ご確認よろしくお願い致します！

2021-09-21 04:55 UTC, u1tnk approved these changes
> 今回の修正の通り理解しましたが、もし認識齟齬ありましたらご指摘お願い致します🙇‍♀️

大丈夫です 🙆‍♀️ 

データ処理と出力の分離ですが、 https://bootcamp.fjord.jp/practices/160 の「終わったら」の項目にある伊藤さんのお手本を見てみてください。綺麗に分離されていますので。

2021-09-21 08:49 UTC, pctapitapitapi commented
ご確認頂きありがとうございました！
マージさせて頂きます🙇‍♀️

2021-09-21 08:51 UTC, merged