wcコマンド提出
pctapitapitapi/ruby-practices pull request #5
Opened 2021-09-24 02:27 UTC by pctapitapitapi

wcコマンドを提出致します！

`main`メソッド が長すぎるのは承知しており、リファクタリングを試みましたが今の私ではこれが限界でした。
ご教示頂ければ幸いです🙇‍♀️

ご確認何卒よろしくお願い致します🙏

2021-09-29 13:08 UTC, u1tnk requested changes
メソッドの使い方や共通化のしかたなど、このプラクティスで求められてるレベルは十分だと思います 👍 
変数名は知識だけですしね。
mainメソッドはこのまま通しても良いレベルですが、気にされてるようですし、せっかくなので分割に挑戦してみましょう 💪

2021-09-29 13:08 UTC, u1tnk commented on 06.wc/wc.rb
> +  opt = OptionParser.new
mainは機能単位でざっくり分けましょう。
まずは入力の処理ですかね。
必要な情報を変数に入れる方法を悩まれると思うのですが、メソッドで返してあげれば良いですよ。
rubyには複数値を返す方法とか、hashや配列に入れる…とかデータをまとめて返す方法は色々あるので、ARGVを渡して、必要な情報が返ってくるようにすると良いと思います。

2021-09-29 13:08 UTC, u1tnk commented on 06.wc/wc.rb
> +  final_total = { lines: 0, words: 0, letters: 0 }
hashにデータまとめてるの良いですね 👍 入力を処理した情報もこんな感じでまとめると良いですよ。

2021-09-29 13:08 UTC, u1tnk commented on 06.wc/wc.rb
> +  file_name_array.each do |file_name|
慣習的にruby界隈は(railsのせいとは思います)複数系にすると配列となるので、ここは `file_names`が良いですね。

2021-09-29 13:08 UTC, u1tnk commented on 06.wc/wc.rb
> +  return unless file_name_array.size > 1
unlessは unlessの方が簡潔に書けるときには使います ( 例: `return unless hoge`)が、ifと同じようなものならifの方が分かりやすくなります。
この場合だと `return if file_name_array == 1` で書けますので。
人間、否定が入るとちょっと混乱するんですよね。

2021-09-29 13:08 UTC, u1tnk commented on 06.wc/wc.rb
> +    inputted_lines = $stdin.readlines
ここは難しかったらそのままでも良いですが、
ファイル名が一つのときと標準入力のときはほぼ処理が一緒なので、共通化できるとより良いですね。

2021-10-02 11:44 UTC, pctapitapitapi commented
ご確認頂きありがとうございます🙏
ご教示頂いた方法で`main`メソッドを短縮することが出来ました😂
めちゃくちゃ難しかったですが😇ハッシュに配列を入れて作った値の扱い方に初めて触れたのでとても勉強になりました🙇‍♀️
再度のご確認、よろしくお願い致します！

2021-10-02 13:49 UTC, u1tnk approved these changes

2021-10-02 13:49 UTC, u1tnk commented on 06.wc/wc.rb
> +      show_reading_contents_total(reading_contents_total, file[:name])
`parsed_input[:options][:l]`

はここで見るようにすれば、if文の範囲が減りますね。
`built_total(file[:content])`
option -l. のときは不要なので無駄になるから今の位置で分岐してるんだと思いますが、コストの小さい処理であればちょっとした無駄より読みやすさの方を重視してかまいません。

ちなみにコストの大きい処理というのはデータベース接続やファイルを読むとかのイメージです。

2021-10-02 13:49 UTC, u1tnk commented on 06.wc/wc.rb
> +    files: files
`files: built_files(argv)` みたいに書いちゃって良いですよ。一行減ります 💪

2021-10-02 13:49 UTC, u1tnk commented on 06.wc/wc.rb
> +  if argv.empty?
👍

2021-10-03 14:07 UTC, u1tnk approved these changes
問題ありません。お疲れ様でした 👍

2021-10-04 00:10 UTC, pctapitapitapi commented
ご教示頂きありがとうございました！！🙇‍♀️
マージさせて頂きます🙏

2021-10-04 00:10 UTC, merged